//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KumariCinemaSystem.Pages
{


    public partial class Booking
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.GridView gvBookings;
        protected global::System.Web.UI.WebControls.DropDownList ddlUserID;
        protected global::System.Web.UI.WebControls.DropDownList ddlShowID;
        protected global::System.Web.UI.WebControls.Button btnBook;
    }
}

