//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KumariCinemaSystem.Pages
{


    public partial class Movies
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.GridView gvMovies;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDuration;
        protected global::System.Web.UI.WebControls.TextBox txtLanguage;
        protected global::System.Web.UI.WebControls.TextBox txtGenre;
        protected global::System.Web.UI.WebControls.TextBox txtReleaseDate;
        protected global::System.Web.UI.WebControls.Button btnAddMovie;
    }
}

