//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KumariCinemaSystem.Pages
{


    public partial class ShowTimes
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.GridView gvShowTimes;
        protected global::System.Web.UI.WebControls.TextBox txtMovieID;
        protected global::System.Web.UI.WebControls.TextBox txtHallID;
        protected global::System.Web.UI.WebControls.DropDownList ddlShowTime;
        protected global::System.Web.UI.WebControls.TextBox txtShowDate;
        protected global::System.Web.UI.WebControls.TextBox txtPrice;
        protected global::System.Web.UI.WebControls.Button btnAddShow;
    }
}

