//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KumariCinemaSystem.Pages
{


    public partial class TheatreCityHall
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.GridView gvHalls;
        protected global::System.Web.UI.WebControls.TextBox txtTheatreID;
        protected global::System.Web.UI.WebControls.TextBox txtCapacity;
        protected global::System.Web.UI.WebControls.Button btnAddHall;
    }
}

